#pragma once
#include "Common.h"

constexpr u32 NUM_FRAMES = 3;
constexpr u32 MAX_DESC_SETS = 1000;
constexpr u32 MAX_DESC_UNIFORM_BUFFERS = 100;
constexpr u32 MAX_DESC_IMAGE_SAMPLERS = 100;
constexpr u32 MAX_DESC_ACCELERATION_STRUCTURES = 100;
constexpr u32 MAX_DESC_STORAGE_IMAGES = 100;
constexpr u32 MAX_DESC_STORAGE_BUFFERS = 100;
constexpr u32 MAX_DESC_COMBINED_IMAGE_SAMPLERS = 100;

#define VALIDATION_LAYERS 0
